spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
    host: ${REDIS_HOST:ingot-db-redis}
    port: ${REDIS_PORT:6379}
    jedis:
      pool:
        max-active: 20
  datasource:
    url: jdbc:mysql://ingot-db-mysql:3306/ingot_uc_db?useUnicode=true&characterEncoding=UTF8&useSSL=false

mybatis:
  type-aliases-package: com.ingot.uc.model.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: true
  mappers: com.ingot.common.mybatis.MyMapper
  identity: MYSQL

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: ingotClientUcSecret
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: ingot-resource-uc
      user-info-uri: http://ingot-auth-center:8050/user
      prefer-token-info: false
      jwt:
        key-uri: http://ingot-auth-center:8050/oauth/token_key

ingot:
  application:
    dataCenterId: 1
    machineId: 0
  oauth2:
    resource:
      permit:
        - /token
        - /test/auth
