spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://ingot-db-mysql:3306/ingot_ac_db?useUnicode=true&characterEncoding=UTF8&useSSL=false

mybatis:
  type-aliases-package: com.ingot.auth.model.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: true
  mappers: com.ingot.common.mybatis.MyMapper
  identity: MYSQL

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: ingotClientAcSecret
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: ingot-resource-ac

ingot:
  application:
    dataCenterId: 0
    machineId: 0
  oauth2:
    tokenStore: jwt
    rsaSecret: 1asd21!@#asd12
    resource:
      permit:
      - /login
      - /test/a
